version: "3.7"

services:
  postgres:
    image: postgres:14
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/pgdata

  odoo:
    image: odoo:16
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8069:8069"
    environment:
      - ODOO_DB_HOST=db
      - ODOO_FONT_NAME=${ODOO_FONT_NAME}
    volumes:
      - data:/var/lib/odoo

volumes:
  data:
  db:

